# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release packages

on:
  push:
    tags:
      - "v*"

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o Hirsipuu-linux-${{github.ref_name}} Hirsipuu.go
    - uses: actions/upload-artifact@v3
      with:
        name: ${{github.ref_name}}
        path: Hirsipuu-linux-${{github.ref_name}}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.ref_name}}
        release_name: Hirsipuu-linux-${{github.ref_name}}
        draft: false
        prerelease: false
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o Hirsipuu-win-${{github.ref_name}}.exe Hirsipuu.go
      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.ref_name}}
          path: Hirsipuu-win-${{github.ref_name}}.exe
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: Hirsipuu-win-${{github.ref_name}}
          draft: false
          prerelease: false
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o Hirsipuu-mac-${{github.ref_name}} Hirsipuu.go
      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.ref_name}}
          path: Hirsipuu-mac-${{github.ref_name}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: Hirsipuu-mac-${{github.ref_name}}
          draft: false
          prerelease: false
    
